import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { attributesApi } from '../../api/attributesApi';
import type { AttributeDefinition, AttributeRequest, AttributeDataType } from '../../types/catalog';
import { PageTitle, ErrorNotice, Loading, Empty, DeleteButton } from '../../components/common/Ui';
import { Field } from '../../components/forms/Fields';
import { text, nullable } from '../../utils/forms';
export function Attributes() {
 const [editing,setEditing]=useState<AttributeDefinition|null|undefined>(undefined);const [notice,setNotice]=useState('');
 const qc=useQueryClient();const query=useQuery({queryKey:['attributes'],queryFn:attributesApi.list});
 const save=useMutation({mutationFn:({id,data}:{id:number|null;data:AttributeRequest})=>attributesApi.save(id,data),onSuccess:()=>{void qc.invalidateQueries();setEditing(undefined);setNotice('Özellik kaydedildi.');}});
 const remove=useMutation({mutationFn:attributesApi.remove,onSuccess:()=>{void qc.invalidateQueries({queryKey:['attributes']});setNotice('Özellik silindi.');}});
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);save.mutate({id:editing?.id??null,data:{name:text(d,'name'),code:text(d,'code'),dataType:text(d,'dataType') as AttributeDataType,unit:nullable(d,'unit'),description:nullable(d,'description')}});}
 return <><PageTitle title="Teknik özellikler" description="Bir kez tanımlayın, farklı kategorilerde tekrar kullanın." action={<button className="primary" onClick={()=>{setEditing(null);save.reset();}}>+ Yeni özellik</button>}/>{notice&&<div role="status" className="notice success">{notice}</div>}<ErrorNotice error={query.error||save.error||remove.error}/>
 {editing!==undefined&&<section className="panel"><h2>{editing?'Özelliği düzenle':'Yeni özellik'}</h2><form key={editing?.id??'new'} onSubmit={submit} className="form-grid"><Field label="Özellik adı"><input name="name" required maxLength={150} defaultValue={editing?.name}/></Field><Field label="Kod" hint="Küçük harf, rakam ve alt çizgi. Oluşturulduktan sonra değiştirilemez."><input name="code" required maxLength={150} pattern="[a-z][a-z0-9_]*" readOnly={!!editing} defaultValue={editing?.code}/></Field><Field label="Veri tipi"><select name="dataType" defaultValue={editing?.dataType??'Text'}>{['Text','Number','Boolean','Date'].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Birim"><input name="unit" maxLength={50} placeholder="GB, Hz, inch…" defaultValue={editing?.unit??''}/></Field><Field label="Açıklama"><textarea name="description" maxLength={500} defaultValue={editing?.description??''}/></Field><div className="form-actions"><button className="primary" disabled={save.isPending}>Kaydet</button><button type="button" onClick={()=>setEditing(undefined)}>Vazgeç</button></div></form></section>}
 {query.isPending?<Loading/>:<section className="panel table-wrap"><table><thead><tr><th>Özellik</th><th>Kod</th><th>Veri tipi</th><th>Birim</th><th>Açıklama</th><th>İşlemler</th></tr></thead><tbody>{query.data?.map(a=><tr key={a.id}><td><strong>{a.name}</strong></td><td><code>{a.code}</code></td><td><span className="badge">{a.dataType}</span></td><td>{a.unit??'—'}</td><td>{a.description??'—'}</td><td><div className="actions"><button className="small" onClick={()=>{setEditing(a);save.reset();}}>Düzenle</button><DeleteButton pending={remove.isPending} onDelete={()=>remove.mutate(a.id)}/></div></td></tr>)}</tbody></table>{query.data?.length===0&&<Empty/>}</section>}</>;
}
