import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { productsApi } from '../../api/productsApi';
import { categoriesApi } from '../../api/categoriesApi';
import { brandsApi } from '../../api/brandsApi';
import { PageTitle, Loading, ErrorNotice, Empty, ProductImage, Status, DeleteButton } from '../../components/common/Ui';
export function Products(){
 const [category,setCategory]=useState('');const [brand,setBrand]=useState('');const [active,setActive]=useState('');const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(20);const qc=useQueryClient();
 const categories=useQuery({queryKey:['categories'],queryFn:categoriesApi.list});const brands=useQuery({queryKey:['brands'],queryFn:brandsApi.list});
 const filters={categoryId:Number(category)||undefined,brandId:Number(brand)||undefined,isActive:active===''?undefined:active==='true',page,pageSize};
 const query=useQuery({queryKey:['products',filters],queryFn:()=>productsApi.list(filters)});
 const remove=useMutation({mutationFn:productsApi.remove,onSuccess:()=>{if(query.data?.items.length===1&&page>1)setPage(page-1);void qc.invalidateQueries({queryKey:['products']});}});
 return <><PageTitle title="Ürünler" description="Kataloğunuzdaki ürünleri keşfedin, düzenleyin ve güncel tutun." action={<Link className="button primary" to="/admin/products/new">+ Yeni ürün</Link>}/><div className="filters panel"><label>Kategori<select value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">Tüm kategoriler</option>{categories.data?.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Marka<select value={brand} onChange={e=>{setBrand(e.target.value);setPage(1);}}><option value="">Tüm markalar</option>{brands.data?.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>Durum<select value={active} onChange={e=>{setActive(e.target.value);setPage(1);}}><option value="">Tümü</option><option value="true">Aktif</option><option value="false">Pasif</option></select></label><label>Sayfa boyutu<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}}>{[10,20,50,100].map(n=><option key={n}>{n}</option>)}</select></label></div>
 <ErrorNotice error={query.error||categories.error||brands.error||remove.error}/>{query.isPending?<Loading/>:<section className="panel table-wrap"><table><thead><tr><th>Ürün</th><th>Marka / Kategori</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody>{query.data?.items.map(p=><tr key={p.id}><td><div className="product-cell"><ProductImage key={p.mainImageUrl} src={p.mainImageUrl} name={p.name}/><Link to={'/admin/products/'+p.id}><strong>{p.name}</strong><small>{p.modelCode??p.slug}</small></Link></div></td><td>{p.brand.name}<small>{p.category.name}</small></td><td><Status active={p.isActive}/></td><td><div className="actions"><Link className="button small" to={'/admin/products/'+p.id}>Görüntüle</Link><Link className="button small" to={'/admin/products/'+p.id+'/edit'}>Düzenle</Link><DeleteButton pending={remove.isPending} onDelete={()=>remove.mutate(p.id)}/></div></td></tr>)}</tbody></table>{query.data?.items.length===0&&<Empty>Bu filtrelere uygun ürün bulunmuyor.</Empty>}<div className="pagination"><span>{query.data?.totalCount??0} ürün · Sayfa {page} / {Math.max(1,query.data?.totalPages??1)}</span><div className="actions"><button disabled={page===1} onClick={()=>setPage(page-1)}>← Önceki</button><button disabled={!query.data||page>=query.data.totalPages} onClick={()=>setPage(page+1)}>Sonraki →</button></div></div></section>}</>;
}

