import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { categoriesApi } from '../../api/categoriesApi';
import type { Category, CategoryRequest } from '../../types/catalog';
import { PageTitle, ErrorNotice, Loading, Empty, Status, DeleteButton } from '../../components/common/Ui';
import { Field, Check } from '../../components/forms/Fields';
import { text } from '../../utils/forms';
export function Categories() {
 const [editing,setEditing]=useState<Category|null|undefined>(undefined);const [notice,setNotice]=useState('');
 const qc=useQueryClient();const query=useQuery({queryKey:['categories'],queryFn:categoriesApi.list});
 const save=useMutation({mutationFn:({id,data}:{id:number|null;data:CategoryRequest})=>categoriesApi.save(id,data),onSuccess:()=>{void qc.invalidateQueries({queryKey:['categories']});setEditing(undefined);setNotice('Kategori kaydedildi.');}});
 const remove=useMutation({mutationFn:categoriesApi.remove,onSuccess:()=>{void qc.invalidateQueries({queryKey:['categories']});setNotice('Kategori silindi.');}});
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);save.mutate({id:editing?.id??null,data:{name:text(d,'name'),parentCategoryId:Number(d.get('parentCategoryId'))||null,displayOrder:Number(d.get('displayOrder')),isActive:d.has('isActive')}});}
 function allowedParent(c:Category){let cursor:Category|undefined=c;const seen=new Set<number>();while(cursor){if(cursor.id===editing?.id||seen.has(cursor.id))return false;seen.add(cursor.id);cursor=query.data?.find(x=>x.id===cursor?.parentCategoryId);}return true;}
 return <><PageTitle title="Kategoriler" description="Ürünlerinize bir yer açın. Kategori yapısını ve teknik özelliklerini düzenleyin." action={<button className="primary" onClick={()=>{setEditing(null);save.reset();}}>+ Yeni kategori</button>}/>{notice&&<div role="status" className="notice success">{notice}</div>}<ErrorNotice error={query.error||save.error||remove.error}/>
 {editing!==undefined&&<section className="panel"><h2>{editing?'Kategoriyi düzenle':'Yeni kategori'}</h2><form key={editing?.id??'new'} onSubmit={submit} className="form-grid"><Field label="Kategori adı"><input name="name" required maxLength={200} defaultValue={editing?.name}/></Field><Field label="Üst kategori"><select name="parentCategoryId" defaultValue={editing?.parentCategoryId??''}><option value="">Üst kategori yok</option>{query.data?.filter(allowedParent).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Görüntüleme sırası"><input name="displayOrder" type="number" step="1" required defaultValue={editing?.displayOrder??0}/></Field><Check name="isActive" label="Aktif" value={editing?.isActive??true}/><div className="form-actions"><button className="primary" disabled={save.isPending}>Kaydet</button><button type="button" onClick={()=>setEditing(undefined)}>Vazgeç</button></div></form></section>}
 {query.isPending?<Loading/>:<section className="panel table-wrap"><table><thead><tr><th>Kategori</th><th>Slug</th><th>Üst kategori</th><th>Sıra</th><th>Durum</th><th>İşlemler</th></tr></thead><tbody>{query.data?.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td className="muted">{c.slug}</td><td>{query.data.find(p=>p.id===c.parentCategoryId)?.name??'—'}</td><td>{c.displayOrder}</td><td><Status active={c.isActive}/></td><td><div className="actions"><Link className="button small" to={'/admin/categories/'+c.id+'/attributes'}>Özellikler</Link><button className="small" onClick={()=>{setEditing(c);save.reset();}}>Düzenle</button><DeleteButton pending={remove.isPending} onDelete={()=>remove.mutate(c.id)}/></div></td></tr>)}</tbody></table>{query.data?.length===0&&<Empty/>}</section>}</>;
}
